ARG NODE_VERSION=16.15.0

FROM node:${NODE_VERSION}-alpine as builder

ARG NEXT_PUBLIC_TOKEN_PATH
ARG NEXT_PUBLIC_API_MOCKING
ARG NEXT_PUBLIC_BUILD_STORYBOOK
ARG NEXT_PUBLIC_TARGET
ARG NEXT_PUBLIC_API_PREFIX
ARG NEXT_PUBLIC_COMPANY_PHONE_NUMBER
ARG NEXT_PUBLIC_CLIENT_ID
ARG NEXT_PUBLIC_CLIENT_SECRET
ARG NEXT_PUBLIC_SPRINT_NUMBER
ARG NEXT_PUBLIC_DATE_STAMP

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY . .

RUN yarn install --frozen-lockfile && \
    yarn build

FROM node:${NODE_VERSION} AS prod

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/next-i18next.config.js ./next-i18next.config.js

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node", "server.js"]
