version: '3.4'
services:
  frontend:
    image: ${CONTAINER_REGISTRY_BASE}/frontend:${CONTAINER_VERSION}
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - '8888:80'
