version: '3.4'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    env_file:
      - .env.development
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:rw,cached
