export const STEP_TYPE_BOOKING = 0
export const STEP_TYPE_PAYMENT = 1
export const STEP_TYPE_INTERNATIONAL_SHIPPING = 2
export const STEP_CUSTOMS_CLEARANCE = 3
export const STEP_LOCAL_DELIVERY = 4

export const STATUS_BOOKING_WAITING_FOR_PAYMENT = 10
export const STATUS_BOOKING_WAITING_FOR_USER_INPUT = 11
export const STATUS_BOOKING_CANCELLATION_BY_USER = 12
export const STATUS_BOOKING_CANCELLATION_BY_MANAGER = 13
export const STATUS_BOOKING_WAITING_FOR_BOOKING_ANTCAR = 14
export const STATUS_BOOKING_SUCCESS = 15
export const STATUS_BOOKING_PAYMENT_ERROR = 16
export const STATUS_BOOKING_TIME_IS_OVER = 17

export const STATUS_PAYMENT_CHOICE_OF_METHOD = 20
export const STATUS_PAYMENT_WAITING_FOR_INPUT = 21
export const STATUS_PAYMENT_WAITING_FOR_USER_PAYMENT = 22
export const STATUS_PAYMENT_WAITING_FOR_RECEPTION_CASH_DESK = 23
export const STATUS_PAYMENT_DEADLINE_AWAITING_PAYMENT = 24
export const STATUS_PAYMENT_PAYMENT_CANCELLATION = 25
export const STATUS_PAYMENT_USER_PAYMENT_SUCCESS = 26
export const STATUS_PAYMENT_SUCCESS_RECEPTION_BOX_OFFICE = 27
export const STATUS_PAYMENT_AUTO_PAYMENT_ANTCAR_ERROR = 28
export const STATUS_PAYMENT_SUCCESS_PAYMENT = 29

export const STATUS_INTERNATIONAL_SHIPPING_WAITING_FOR_USER_PAYMENT = 30
export const STATUS_INTERNATIONAL_SHIPPING_WAITING_FOR_PAYMENT_ANTCAR = 31
export const STATUS_INTERNATIONAL_SHIPPING_DEADLINE_AWAITING_PAYMENT = 32
export const STATUS_INTERNATIONAL_SHIPPING_STOP = 33
export const STATUS_INTERNATIONAL_SHIPPING_USER_PAYMENT_SUCCESS = 34
export const STATUS_INTERNATIONAL_SHIPPING_PAYMENT_ANTCAR_ERROR = 35
export const STATUS_INTERNATIONAL_SHIPPING_PAYMENT_ANTCAR_SUCCESS = 36
export const STATUS_INTERNATIONAL_SHIPPING_NOT_DELIVERY = 37
export const STATUS_INTERNATIONAL_SHIPPING_SUCCESS = 38

export const STATUS_CUSTOMS_CLEARANCE_WAITING_FOR_USER_PAYMENT = 40
export const STATUS_CUSTOMS_CLEARANCE_WAITING_FOR_PAYMENT_ANTCAR = 41
export const STATUS_CUSTOMS_CLEARANCE_STOP = 42
export const STATUS_CUSTOMS_CLEARANCE_SUCCESS = 43

export const STATUS_LOCAL_DELIVERY_WAITING_FOR_USER_PAYMENT = 50
export const STATUS_LOCAL_DELIVERY_WAITING_FOR_PAYMENT_ANTCAR = 51
export const STATUS_LOCAL_DELIVERY_DEADLINE_AWAITING_USER_PAYMENT = 52
export const STATUS_LOCAL_DELIVERY_STOP = 53
export const STATUS_LOCAL_DELIVERY_USER_PAYMENT_SUCCESS = 54
export const STATUS_LOCAL_DELIVERY_PAYMENT_ANTCAR_ERROR = 55
export const STATUS_LOCAL_DELIVERY_PAYMENT_ANTCAR_SUCCESS = 56
export const STATUS_LOCAL_DELIVERY_NOT_DELIVERY = 57
export const STATUS_LOCAL_DELIVERY_SUCCESS = 58

export const VIEWER_TIME_TO_PAY_IN_MINUTES = 30

export const ORDER_STEP_TEXT = {
  [STEP_TYPE_BOOKING]: 'Booking',
  [STEP_TYPE_PAYMENT]: 'Car payment',
  [STEP_TYPE_INTERNATIONAL_SHIPPING]: 'Shipping',
  [STEP_CUSTOMS_CLEARANCE]: 'Customs',
  [STEP_LOCAL_DELIVERY]: 'Local Delivery',
}

export const ORDER_STATUS_TEXT = {
  // Booking status
  [STATUS_BOOKING_WAITING_FOR_PAYMENT]: 'Pay the bill',
  [STATUS_BOOKING_WAITING_FOR_USER_INPUT]: 'Fill in the details',
  [STATUS_BOOKING_CANCELLATION_BY_USER]: 'Cancel By User',
  [STATUS_BOOKING_CANCELLATION_BY_MANAGER]: 'Cancel By Manager',
  [STATUS_BOOKING_WAITING_FOR_BOOKING_ANTCAR]: '',
  [STATUS_BOOKING_SUCCESS]: 'Booking Success',
  [STATUS_BOOKING_PAYMENT_ERROR]: 'Booking Error',
  [STATUS_BOOKING_TIME_IS_OVER]: 'Time is over',
  // Payment status
  [STATUS_PAYMENT_CHOICE_OF_METHOD]: 'Choice of method',
  [STATUS_PAYMENT_WAITING_FOR_INPUT]: 'Fill in the details',
  [STATUS_PAYMENT_WAITING_FOR_USER_PAYMENT]: 'Pay the bill',
  [STATUS_PAYMENT_WAITING_FOR_RECEPTION_CASH_DESK]: 'Reception',
  [STATUS_PAYMENT_DEADLINE_AWAITING_PAYMENT]: 'Deadline payment',
  [STATUS_PAYMENT_PAYMENT_CANCELLATION]: 'Cancel',
  [STATUS_PAYMENT_USER_PAYMENT_SUCCESS]: 'Payment success',
  [STATUS_PAYMENT_SUCCESS_RECEPTION_BOX_OFFICE]: 'Reception',
  [STATUS_PAYMENT_AUTO_PAYMENT_ANTCAR_ERROR]: 'Payment error',
  [STATUS_PAYMENT_SUCCESS_PAYMENT]: 'Payment success',
  // Shipping status
  [STATUS_INTERNATIONAL_SHIPPING_WAITING_FOR_USER_PAYMENT]: 'Pay the bill',
  [STATUS_INTERNATIONAL_SHIPPING_WAITING_FOR_PAYMENT_ANTCAR]: '',
  [STATUS_INTERNATIONAL_SHIPPING_DEADLINE_AWAITING_PAYMENT]: 'Deadline payment',
  [STATUS_INTERNATIONAL_SHIPPING_STOP]: 'Shipping stop',
  [STATUS_INTERNATIONAL_SHIPPING_USER_PAYMENT_SUCCESS]: 'Payment success',
  [STATUS_INTERNATIONAL_SHIPPING_PAYMENT_ANTCAR_ERROR]: 'Payment error',
  [STATUS_INTERNATIONAL_SHIPPING_PAYMENT_ANTCAR_SUCCESS]: 'Payment success',
  [STATUS_INTERNATIONAL_SHIPPING_NOT_DELIVERY]: 'Not delivered',
  [STATUS_INTERNATIONAL_SHIPPING_SUCCESS]: 'Shipping success',
  // Customs status
  [STATUS_CUSTOMS_CLEARANCE_WAITING_FOR_USER_PAYMENT]: 'Pay the bill',
  [STATUS_CUSTOMS_CLEARANCE_WAITING_FOR_PAYMENT_ANTCAR]: '',
  [STATUS_CUSTOMS_CLEARANCE_STOP]: 'Customs stop',
  [STATUS_CUSTOMS_CLEARANCE_SUCCESS]: 'Customs success',
  // Local Deliver status
  [STATUS_LOCAL_DELIVERY_WAITING_FOR_USER_PAYMENT]: 'Pay the bill',
  [STATUS_LOCAL_DELIVERY_WAITING_FOR_PAYMENT_ANTCAR]: '',
  [STATUS_LOCAL_DELIVERY_DEADLINE_AWAITING_USER_PAYMENT]: 'Deadline payment',
  [STATUS_LOCAL_DELIVERY_STOP]: 'Deliver stop',
  [STATUS_LOCAL_DELIVERY_USER_PAYMENT_SUCCESS]: 'Payment success',
  [STATUS_LOCAL_DELIVERY_PAYMENT_ANTCAR_ERROR]: 'Payment error',
  [STATUS_LOCAL_DELIVERY_PAYMENT_ANTCAR_SUCCESS]: 'Payment success',
  [STATUS_LOCAL_DELIVERY_NOT_DELIVERY]: 'Not delivered',
  [STATUS_LOCAL_DELIVERY_SUCCESS]: 'Delivered',
}

export const ORDER_STATUS_DELETING = [
  STATUS_BOOKING_CANCELLATION_BY_USER,
  STATUS_BOOKING_CANCELLATION_BY_MANAGER,
  STATUS_BOOKING_TIME_IS_OVER,
]

export const ORDER_STATUS_USER_PAYMENT = [
  STATUS_BOOKING_WAITING_FOR_PAYMENT,
  STATUS_PAYMENT_WAITING_FOR_USER_PAYMENT,
  STATUS_INTERNATIONAL_SHIPPING_WAITING_FOR_USER_PAYMENT,
  STATUS_CUSTOMS_CLEARANCE_WAITING_FOR_USER_PAYMENT,
  STATUS_LOCAL_DELIVERY_WAITING_FOR_USER_PAYMENT,
]

export const ORDER_STATUS_WITH_LINK = [STATUS_BOOKING_PAYMENT_ERROR, STATUS_BOOKING_SUCCESS]

export const ORDER_STATUS_WITH_BOOKING_LINK = [STATUS_BOOKING_WAITING_FOR_PAYMENT, STATUS_BOOKING_PAYMENT_ERROR]

export const ORDERS_REQUEST_TARGET = '/orders'

export const ORDERS_COLLECTION_PRIMARY_KEY = [ORDERS_REQUEST_TARGET, 'orders-collection']

export const ORDER_CREATE_PRIMARY_KEY = [ORDERS_REQUEST_TARGET, 'order-create']

export const ORDER_REQUEST_TARGET = '/orders/:id'

export const ORDER_SINGLE_PRIMARY_KEY = [ORDER_REQUEST_TARGET, 'order-single']

export const ORDER_PAY_REQUEST_TARGET = '/orders/:id/pay'

export const ORDER_PAY_PRIMARY_KEY = [ORDER_PAY_REQUEST_TARGET, 'order-pay']

export const PAYMENTS_REQUEST_TARGET = '/payments'

export const PAYMENTS_COLLECTION_PRIMARY_KEY = [PAYMENTS_REQUEST_TARGET, 'payments-collection']

export const ORDER_PAGE_STATUS_TEXT = {
  // Booking status
  [STATUS_BOOKING_WAITING_FOR_PAYMENT]: 'Pay the bill',
  [STATUS_BOOKING_WAITING_FOR_USER_INPUT]: 'Fill in the details',
  [STATUS_BOOKING_CANCELLATION_BY_USER]: 'Cancel By User',
  [STATUS_BOOKING_CANCELLATION_BY_MANAGER]: 'Cancel By Manager',
  [STATUS_BOOKING_WAITING_FOR_BOOKING_ANTCAR]: '',
  [STATUS_BOOKING_SUCCESS]: 'Booking Success',
  [STATUS_BOOKING_PAYMENT_ERROR]: 'Booking Error',
  [STATUS_BOOKING_TIME_IS_OVER]: 'Time is over',
  // Payment status
  [STATUS_PAYMENT_CHOICE_OF_METHOD]: 'Choice of method',
  [STATUS_PAYMENT_WAITING_FOR_INPUT]: 'Fill in the details',
  [STATUS_PAYMENT_WAITING_FOR_USER_PAYMENT]: 'Pay the bill',
  [STATUS_PAYMENT_WAITING_FOR_RECEPTION_CASH_DESK]: 'Reception',
  [STATUS_PAYMENT_DEADLINE_AWAITING_PAYMENT]: 'Deadline payment',
  [STATUS_PAYMENT_PAYMENT_CANCELLATION]: 'Cancel',
  [STATUS_PAYMENT_USER_PAYMENT_SUCCESS]: 'Payment success',
  [STATUS_PAYMENT_SUCCESS_RECEPTION_BOX_OFFICE]: 'Reception',
  [STATUS_PAYMENT_AUTO_PAYMENT_ANTCAR_ERROR]: 'Payment error',
  [STATUS_PAYMENT_SUCCESS_PAYMENT]: 'Payment success',
  // Shipping status
  [STATUS_INTERNATIONAL_SHIPPING_WAITING_FOR_USER_PAYMENT]: 'Pay the bill',
  [STATUS_INTERNATIONAL_SHIPPING_WAITING_FOR_PAYMENT_ANTCAR]: '',
  [STATUS_INTERNATIONAL_SHIPPING_DEADLINE_AWAITING_PAYMENT]: 'Deadline payment',
  [STATUS_INTERNATIONAL_SHIPPING_STOP]: 'Shipping stop',
  [STATUS_INTERNATIONAL_SHIPPING_USER_PAYMENT_SUCCESS]: 'Payment success',
  [STATUS_INTERNATIONAL_SHIPPING_PAYMENT_ANTCAR_ERROR]: 'Payment error',
  [STATUS_INTERNATIONAL_SHIPPING_PAYMENT_ANTCAR_SUCCESS]: 'Payment success',
  [STATUS_INTERNATIONAL_SHIPPING_NOT_DELIVERY]: 'Not delivered',
  [STATUS_INTERNATIONAL_SHIPPING_SUCCESS]: 'Shipping success',
  // Customs status
  [STATUS_CUSTOMS_CLEARANCE_WAITING_FOR_USER_PAYMENT]: 'Pay the bill',
  [STATUS_CUSTOMS_CLEARANCE_WAITING_FOR_PAYMENT_ANTCAR]: '',
  [STATUS_CUSTOMS_CLEARANCE_STOP]: 'Customs stop',
  [STATUS_CUSTOMS_CLEARANCE_SUCCESS]: 'Customs success',
  // Local Deliver status
  [STATUS_LOCAL_DELIVERY_WAITING_FOR_USER_PAYMENT]: 'Pay the bill',
  [STATUS_LOCAL_DELIVERY_WAITING_FOR_PAYMENT_ANTCAR]: '',
  [STATUS_LOCAL_DELIVERY_DEADLINE_AWAITING_USER_PAYMENT]: 'Deadline payment',
  [STATUS_LOCAL_DELIVERY_STOP]: 'Deliver stop',
  [STATUS_LOCAL_DELIVERY_USER_PAYMENT_SUCCESS]: 'Payment success',
  [STATUS_LOCAL_DELIVERY_PAYMENT_ANTCAR_ERROR]: 'Payment error',
  [STATUS_LOCAL_DELIVERY_PAYMENT_ANTCAR_SUCCESS]: 'Payment success',
  [STATUS_LOCAL_DELIVERY_NOT_DELIVERY]: 'Not delivered',
  [STATUS_LOCAL_DELIVERY_SUCCESS]: 'Delivered',
}
