import Head from 'next/head'
import { NextPageWithLayout } from '@/shared/@types'
import { GetServerSideProps } from 'next'
import { dehydrate, QueryClient } from 'react-query'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { prefetchCarCollection } from '@/entities/car'
import { CatalogView } from '@/views/catalog-view'
import { DEFAULT_ORDER_VALUE } from '@/shared/config'
import { ContentLayout } from '@/layouts/content-layout'

const HomePage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>AntCar</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <CatalogView />
    </>
  )
}

HomePage.Layout = ContentLayout

export const getServerSideProps: GetServerSideProps = async ctx => {
  const { query, locale } = ctx
  const queryClient = new QueryClient()

  const order = query.order ? JSON.parse(query.order as string) : DEFAULT_ORDER_VALUE
  query[order.field] = order.order

  delete query.order

  await prefetchCarCollection(ctx, queryClient, {
    ...query,
    locale,
  })

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      ...(await serverSideTranslations(locale!, ['common', 'product', 'car'])),
    },
  }
}

export default HomePage
